feat(all-pages-panel): added all pages panel
gravity-ui/navigation pull request #109
Opened 2023-09-26 15:17 UTC by catakot

2023-09-27 10:50 UTC, DarkGenius commented on src/components/AllPagesPanel/i18n/index.ts
> +const COMPONENT = 'MobileHeader';
Let fix component name

2023-09-27 10:55 UTC, DarkGenius requested changes
The create button should be at the end of the list

<img width="359" alt="image" src="https://github.com/gravity-ui/navigation/assets/4076124/dbd520f3-b052-42ef-ad66-4c9ae8ecf372">

2023-09-27 16:00 UTC, catakot commented on src/components/AllPagesPanel/AllPagesPanel.tsx
> +    const [isEditMode, setIsActive] = useState(false);
Done

2023-09-28 05:09 UTC, Lunory requested changes

2023-09-28 05:11 UTC, Lunory commented
1. All pages panel doesn’t close by clicking “All pages” menu item
![telegram-cloud-photo-size-2-5235718919879250331-y](https://github.com/gravity-ui/navigation/assets/22904809/cdae108c-b8ed-4fc9-9843-8ca973972333)

2. When you are opening panel from popup, popup doesn’t close
![telegram-cloud-photo-size-2-5235718919879250230-y](https://github.com/gravity-ui/navigation/assets/22904809/aaf4a473-0f64-475f-afaa-9afac29998b5)

2023-09-28 08:17 UTC, DarkGenius reviewed
lunory@ up: _FIXED_

The element "All pages" should be highlighted while the panel is open

<img width="595" alt="image" src="https://github.com/gravity-ui/navigation/assets/4076124/1a7e8266-7e0c-4211-9a38-23ac4b81dbfd">

2023-09-28 10:34 UTC, catakot commented on src/components/AsideHeader/AsideHeader.tsx
>      const size = compact ? ASIDE_HEADER_COMPACT_WIDTH : ASIDE_HEADER_EXPANDED_WIDTH;
fixed

2023-09-28 10:34 UTC, catakot commented on src/components/AsideHeader/useAsideHeaderInnerContextValue.tsx
> +                      },
fixed

2023-09-28 10:35 UTC, catakot commented on src/components/AsideHeader/useAsideHeaderInnerContextValue.tsx
> +            },
fixed

2023-09-28 14:15 UTC, catakot commented on src/components/AllPagesPanel/AllPagesPanel.tsx
> +        //@ts-ignore TODO
done

2023-09-28 17:52 UTC, Lunory commented on src/components/CompositeBar/Item/Item.tsx
> +    console.log(`open ${open}`);
2 logs in this file

2023-09-29 06:56 UTC, DarkGenius approved these changes

2023-09-29 06:58 UTC, Lunory approved these changes

2023-09-29 07:28 UTC, merged