feat(AsideHeadser): Sort elements in AsideHeader
gravity-ui/navigation pull request #337
Opened 2024-12-05 09:27 UTC by jenshenJ

2024-12-09 08:37 UTC, DarkGenius commented on src/components/AllPagesPanel/AllPagesPanel.tsx
> +    }, [onMenuItemsChanged]);
What is the purpose of this dependency if there is no reference to it in the callback code?

2024-12-12 08:52 UTC, jenshenJ commented on src/components/AllPagesPanel/AllPagesPanel.tsx
> +        [isEditMode, togglePageVisibility, onMenuItemsChanged],
Same issue as above

2024-12-12 14:24 UTC, DarkGenius requested changes
<img width="437" alt="image" src="https://github.com/user-attachments/assets/515aa90b-cfed-46d4-897a-528b91e38051" />
- Unpin items stopped working
- Reset order is not working
- What are these elements with dashes?

2025-01-29 08:28 UTC, DarkGenius commented on .storybook/preview.tsx
> -        <React.StrictMode>
Why did you remove StrictMode?

2025-01-29 08:33 UTC, jenshenJ commented on .storybook/preview.tsx
> -        <React.StrictMode>
> Why did you remove StrictMode?

Иecause the react-beautiful-dnd library from uikit doesn't work in StrictMode

2025-01-29 08:36 UTC, DarkGenius requested changes

2025-01-29 08:36 UTC, DarkGenius commented on src/components/AllPagesPanel/AllPagesListItem/AllPagesListItem.tsx
> +    const onItemDrugStart = (e: MouseEvent<HTMLDivElement>) => {
Dr**a**g

2025-01-29 08:36 UTC, DarkGenius commented on src/components/AllPagesPanel/AllPagesListItem/AllPagesListItem.tsx
> +            draggable={editMode}
Shouldn't we check also `enableSorting` there?

2025-01-29 08:36 UTC, DarkGenius commented on src/components/AllPagesPanel/AllPagesPanel.tsx
> +    const [dragingItemTitle, setDragingItemTitle] = useState<ReactNode | null>(null);
dra**g**ging

2025-01-29 08:36 UTC, DarkGenius commented on src/components/AllPagesPanel/i18n/en.json
> +  "all-panel.title.editing": "Configuring the Menu Bar",
I think it's better in lower case

2025-01-30 09:59 UTC, DarkGenius approved these changes

2025-01-30 10:00 UTC, merged